### ISSUE TITLE
Error when browsing to files/images/URLs

### ISSUE THREAD

**Issue by ech01** [DNN-Connect/CKEditorProvider#8]
Using evoq 8.1...
It fires when you create a link and click the "Browser" button.

---

Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 7/27/2015 9:19:16 AM 
Event time (UTC): 7/27/2015 2:19:16 PM 
Event ID: 6a887830ccc349ca8c3eeca324638fde 
Event sequence: 252 
Event occurrence: 2 
Event detail code: 0 

Exception information: 
    Exception type: ArgumentNullException 
    Exception message: Value cannot be null.
Parameter name: format
   at System.String.Format(String format, Object arg0, Object arg1)
   at DNNConnect.CKEditorProvider.Browser.Browser.SetLanguage()
   at DNNConnect.CKEditorProvider.Browser.Browser.Page_Load(Object sender, EventArgs e)
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Request information: 
    Request URL: http://216.176.95.88/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx?Type=Link&tabid=135&PortalID=0&mid=4537&ckid=txtContent&mode=Default&lang=en-US&CKEditor=dnn_ctr4537_EditHTML_txtContent_txtContent&CKEditorFuncNum=1&langCode=en 
    Request path: /Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx 
    User host address: 75.146.147.129 
    User: host 
    Is authenticated: True 
    Authentication Type: Forms 
    Thread account name: IIS APPPOOL\consolidated 

Thread information: 
    Thread ID: 20 
    Thread account name: IIS APPPOOL\consolidated 
    Is impersonating: False 
    Stack trace:    at System.String.Format(String format, Object arg0, Object arg1)
   at DNNConnect.CKEditorProvider.Browser.Browser.SetLanguage()
   at DNNConnect.CKEditorProvider.Browser.Browser.Page_Load(Object sender, EventArgs e)
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by bdukes** [comment]
This appears to be from https://github.com/DNN-Connect/CKEditorProvider/blob/b7c9b068b1695a6b48b97cbe28074ebeaf1d3749/Browser/Browser.aspx.cs#L2276, so the `Localization.GetString` call is returning `null`.  The [`LanguageCode` property](https://github.com/DNN-Connect/CKEditorProvider/blob/b7c9b068b1695a6b48b97cbe28074ebeaf1d3749/Browser/Browser.aspx.cs#L117) there doesn't seem like it would have an issue, so it's probably in the (fairly gnarly) [`ResXFile` property](https://github.com/DNN-Connect/CKEditorProvider/blob/b7c9b068b1695a6b48b97cbe28074ebeaf1d3749/Browser/Browser.aspx.cs#L133),

**Comment by bdukes** [comment]
That's all the time I have for spelunking at the moment.

**Comment by ohine** [comment]
Testing on Platform v7.4.0 (single language) and I can't seem to reproduce. The steps I'm using are as follows.
1. Edit Html module
2. Select some text in the editor
3. Click create link
4. Click 'Browse Server'
5. Popup loads correctly and can insert a link to another page or document without any error.

**Comment by ohine** [comment]
Already fixed in the latest branch. Closing issue.
